apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:6a213e299c1d6ec98aaad2f5f032eaf0d7498ae95662b6638f7b187de7bbe961
        name: container-image
        resources: {}
status: {}
