apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:4793b3585a2a1d4451316f04adcec1ae4e74f33cee06a8f5898e327847e466ac
        name: container-image
        resources: {}
status: {}
