apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:1785de54b6209d091e18953e7b5074b54926bcb78680ab4123782d39a4c5f1a3
        name: container-image
        resources: {}
status: {}
