apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:65aca52411b55dfca09f4ce426dc3ed72e1592bd1b36f81a8ddf02e88c61ca80
        name: container-image
        resources: {}
status: {}
