apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:db04fed31e2e8d90aac49cd74afcc55a1997f17c5dc5f5bb79464f79812af197
        name: container-image
        resources: {}
status: {}
