apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:55d96eace410b9c2260d9c01972f16cb3729aaf0bb514bd910d8c2c980251b5b
        name: container-image
        resources: {}
status: {}
