apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:7a904249406c67ca92415ea373756f8201c9787b599af8acf20dcd942711b730
        name: container-image
        resources: {}
status: {}
