apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:126faee01b30a776dc1e5ef8bc42fe269730940f4fa203d514b602de1d7ecb6f
        name: container-image
        resources: {}
status: {}
