apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:74df584fc167cfdde8d11edec5966de099832516ad18c74ca37e7f863975b0f9
        name: container-image
        resources: {}
status: {}
