apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:aaba714acb028fa2f2ede3d904d96b07bd0eb0e2de4e3ade2634a90c34ab4eb0
        name: container-image
        resources: {}
status: {}
