apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:aeff190c94a03c1d41442a678b2b51b95e0972c5c1a72ae261604161561d3c37
        name: container-image
        resources: {}
status: {}
