apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:9116681f8144ff8cee39e08033f12fa92af0c1cef931b1d79e3e92dc0382af40
        name: container-image
        resources: {}
status: {}
