apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:a2d794f74b27e03e31dfc8f08773aa791fa96f6f828008210ed75525c702d4ed
        name: container-image
        resources: {}
status: {}
