apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: golden-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/ec-golden-image@sha256:aebcf9f8fc52d6f402198d3b7204b66581aea19f15e63b089f005634ba437e80
        name: container-image
        resources: {}
status: {}
